### ISSUE TITLE
Error due to HDSDump or manifest source?

### ISSUE THREAD

**Issue by sonnvl** [WendyH/hdsdump#1]
Unhandled Exception: System.FormatException: Index (zero based) must be greater
than or equal to zero and less than the size of the argument list.
   at System.Text.StringBuilder.AppendFormat(IFormatProvider provider, String fo
rmat, Object[] args)
   at System.String.Format(IFormatProvider provider, String format, Object[] arg
s)
   at hdsdump.F4F.DecodeFragment(Byte[]& frag, Boolean notWrite)
   at hdsdump.F4F.WriteFragment(Byte[]& data, Int32 fragNum)
   at hdsdump.F4F.DownloadFragments(String manifestUrl)
   at hdsdump.Program.Main(String[] args)

**Comment by WendyH** [comment]
Snx. I found error in code and updated the project. It was when using the `--debug` switch?

**Comment by sonnvl** [comment]
I leave here the source for you to test:
http://scache.fptplay.net.vn/livez/vtv6_2500.stream/manifest.f4m

**Comment by WendyH** [comment]
[Worked fine.](http://i.snag.gy/nL7Mu.jpg)
